import Link from "next/link";
import Head from "next/head";

export default function FAQ() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h2>FAQ: HELLO</h2>
            <Link href='/'>
                <a>Inicio</a>
            </Link>
        </>
    );
}
